# Originally based on:
# https://raw.githubusercontent.com/hyperium/hyper/207fca63ce/.appveyor.yml
environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
  - vcpkg install sqlite3:x86-windows
  - vcpkg install sqlite3:x64-windows
  - vcpkg integrate install
build: false
test_script:
  - cargo build
  - cargo test
