[package]
authors = ["Shaun Mangelsdorf <s.mangelsdorf@gmail.com>",
           "Bradley Beddoes <bradleybeddoes@gmail.com>"]
description = "Work in progress library with no initial release yet"
license = "MIT"
name = "gotham"
version = "0.1.0"

[dependencies]
log = "0.3"
# TODO: Return to tracking hyper master once merged
hyper = { git = "https://github.com/gotham-rs/hyper.git", branch = "add-response-body_ref-function" }
mime = "0.3"
futures = "~0.1.11"
futures-cpupool = "0.1"
tokio-core = "*"
tokio-io = "*"
mio = "*"
borrow-bag = "0.3"
url = "1.4.0"
uuid = { version = "0.5", features = ["v4"] }
chrono = "0.3"

[dev-dependencies]
gotham_derive = { path = "gotham_derive" }
