[workspace]
members = [
    "gotham",
    "gotham_derive",

    "middleware/template",
    "middleware/under_development/diesel",

    "misc/borrow_bag",

    "examples/hello_world",
    "examples/hello_router",
    "examples/basic_router",
    "examples/hello_header",
    "examples/basic_into_response",
    "examples/basic_path_extractor",
    "examples/basic_query_extractor",
]
