[package]
authors = ["Shaun Mangelsdorf <s.mangelsdorf@gmail.com>",
           "Bradley Beddoes <bradleybeddoes@gmail.com>"]
description = "Work in progress library with no initial release yet"
license = "MIT"
name = "gotham"
version = "0.1.0"

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper.git" }
futures = "~0.1.11"
tokio-core = "*"
tokio-io = "*"
mio = "*"
borrow-bag = "0.3"
url = "1.4.0"
uuid = { version = "0.5", features = ["v4"] }
