[package]
name = "kitchen-sink"
version = "0.1.0"
authors = ["Shaun Mangelsdorf <s.mangelsdorf@gmail.com>",
           "Bradley Beddoes <bradleybeddoes@gmail.com>"]

[dependencies]
gotham = { path = "../.." }
futures = "*"
hyper = { git = "https://github.com/hyperium/hyper.git" }
pretty_env_logger = "*"
borrow-bag = "*"
